//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Credenciall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highlight
    {
        public int id { get; set; }
        public string hl_header { get; set; }
        public string hl_subtitle { get; set; }
        public Nullable<byte> active { get; set; }
        public string hl_slogan { get; set; }
        public string hl_post_header { get; set; }
        public string hl_post_text { get; set; }
        public string hl_cta { get; set; }
    }
}
