//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Credenciall
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class credenciall_websiteEntities : DbContext
    {
        public credenciall_websiteEntities()
            : base("name=credenciall_websiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Highlight> Highlights { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Slogan> Slogans { get; set; }
    }
}
